### ISSUE TITLE
Just to say thank you.

### ISSUE THREAD

**Issue by julienmoinard** [arturo182/ER-TFT040-2_breakout#1]
Thank you your job that help me to use this screen.

Ps:  I'am looking for a touch screen for this screen but seems to be hard.
BuyDisplay tell me that it is possible to customize one for me but I need to purshase 1000 pcs :)
Do you need touch screen for yours ?

Best regards,
Julien.

**Comment by arturo182** [comment]
Glad to hear you found my board useful :)

Unfortunately, I don't know of any touch screens for the display, sorry.
